name: hooper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  firebase_core: ^4.12.1
  flutter:
    sdk: flutter
  progressive_blur: ^0.0.2
  screen_corner_radius: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true